### PR TITLE
adding outbound integration

### PR DESCRIPTION
**Pull request by usmanity**
Hi, I am working on integrating Outbound with Segment's analytics.js but I am unable to run the test getting an error:

`Error loading resource http://localhost:56227/saucelabs.js (203). Details: Error downloading http://localhost:56227/saucelabs.js - server replied: Not Found`

Would like to get this merged.

### CODE REVIEW

**Comment by reinpk** [comment]
given existing support through the server, why duplicate the code in analytics.js as well?

**Comment by usmanity** [comment]
@reinpk this is to allow using the javascript library which contains client side code to display notifications, and track events in the UI

**Comment by reinpk** [comment]
the events can still flow through our servers as a proxy, but the display notifications are interesting. do you have a screenshot of that?

**Comment by usmanity** [comment]
yes, you can actually see a working demo on my homepage, www.usmanity.com. The way the updated JS library works is by fetching a customer specific library which is based on their a public key that would be set in their outbound account, this then allows the outbound js to talk to the outbound server for notifications. let me know if you weren't able to see the notification, should show up right away when you land on page.

**Comment by reinpk** [comment]
ok cool, @segmentio/integrations will take a look at the next scheduled review/merge, probably on thursday morning

**Comment by f2prateek** [comment]
@usmanity The saucelabs error is normal and it doesn't block your tests from running. 

`Failed to start mocha: Init timeout` is the line that indicates an error in your integration code that analytics.js doesn't do a great job of surfacing. You can try running it in a browser and trace the exception being thrown : `make test-browser integration=outbound —debug`

**Comment by usmanity** [comment]
Hi, I've updated our tests but CircleCI is reporting another library breaking my tests. I am on the latest commit from upstream as of e07a978, which was passing. Let me know if I need to do anything else on my side. Thanks! :smile:

**Comment by amillet89** [comment]
Hey @usmanity looks like that commit is a couple behind, can you rebase against latest master and submit again?

**Comment by usmanity** [comment]
Hi, now I am getting this as the result of the CircleCi run:

````
1) integrations should export our integrations:

      + expected - actual

      +81
      -80
````

Do I need to do anything to the `integrations.js` file?

**Comment by f2prateek** [comment]
@usmanity You'll need to update `test/index.js` - I've pushed a branch here https://github.com/segmentio/analytics.js-integrations/tree/outbound-integration. 

Before we can merge it however, you'll need to add tests to the integration as well. Here's an example of a complete PR to add an integration - https://github.com/segmentio/analytics.js-integrations/pull/595. You can find examples of tests in existing integrations as well.

**Comment by f2prateek** [comment]
@usmanity sorry my bad, didn't realize this had tests. I've rebased and squashed the commits in #596

**Pull request closed without merging**
