### PR TITLE
Add/autosend - Autosend integration

### PR DESCRIPTION
**Pull request by pchukwura**
Logo: https://d1touj61nfw0sa.cloudfront.net/AutosendLogo.eps

This is a pull request to add Autosend integration into Segment.io. I provided a link to the Autosend logo above, as I could not upload a vector image to Github (they only allow gif, jpg, and png apparently)

Description: Proactively message your online customers. Send email or SMS to your customers based on their actions on your website.

### CODE REVIEW

**Comment by harrietgrace** [comment]
Hi @pchukwura, thanks for your PR! If you could please rebase this against the latest version, we can kick off the review process :)

**Comment by pchukwura** [comment]
Hi @harrietgrace Rebase done! The test failure that CircleCI brought up doesn't appear to be Autosend related.

Cheers

**Comment by harrietgrace** [comment]
@pchukwura Thanks for getting onto that so quickly! The error that is failing the tests can be fixed by incrementing the integration count in test/index.js on line 24 :)

**Comment by pchukwura** [comment]
Did you want me to do that? I see you emailed us saying the integration is currently in review.

**Comment by harrietgrace** [comment]
Yes please! I'm happy with the rest of the integration, so once the integration count has been upped, I'll merge it.

**Comment by pchukwura** [comment]
Incremented and passed! :)

**Comment by harrietgrace** [comment]
Thanks! I've just signed up for an Autosend testing account, as I saw that you have an appkey for the tests, where would I find that in my account? 

I also saw that you have a REST API, so if you're interested in doing a server side integration as well let me know! :)

**Comment by pchukwura** [comment]
You can find the app key by going to Messages > Create New Message >  Email/SMS >  REST API   and click on the link next to the red wrench that says "Follow these instructions" (or click JavaScript and copy the snippet).

I am interested in doing the server side integration... point me to your docs so I can get started!

Hope this helps!

**Comment by harrietgrace** [comment]
Awesome, thanks :) 

Contribution docs for server side integrations are [here](https://github.com/segmentio/integrations/blob/master/Contributing.md), and I've set up a repo for you to PR [here](https://github.com/segmentio/integration-autosend). Feel free to email integrations@segment.com if you have any questions, and I'll help you out!

**Comment by pchukwura** [comment]
I'll get started with the server side integration! Btw, this wouldn't stop
the analytics.js integration that I already did and you guys are reviewing
would it?



On Fri, Jan 23, 2015 at 5:43 PM, Harriet Lawrence <notifications@github.com>
wrote:

> Merged #382
> <https://github.com/segmentio/analytics.js-integrations/pull/382>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/segmentio/analytics.js-integrations/pull/382#event-224083730>
> .
>



-- 
-Patrick Chukwura

**Comment by harrietgrace** [comment]
That's all complete, I merged it yesterday. It will go out with our Monday deploy :)

**Comment by pchukwura** [comment]
Hi Harriet,

I didn't see the Autosend integration on segment.com/integrations or see
the code merged on any of the latest commits here:
https://github.com/segmentio/analytics.js/commits/master

Just checking in to see if there are any issues?

Thanks

On Sat, Jan 24, 2015 at 12:26 PM, Harriet Lawrence <notifications@github.com
> wrote:

> That's all complete, I merged it yesterday. It will go out with our Monday
> deploy :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/segmentio/analytics.js-integrations/pull/382#issuecomment-71335739>
> .
>



-- 
-Patrick Chukwura

**Comment by harrietgrace** [comment]
Hey Patrick, thanks for checking in, sorry that it didn't end up going out yesterday. There were a couple of minor holdups getting all the metadata ready to go, but that's all resolved. I didn't end up deploying at all yesterday, but it will definitely happen this week. I'll ping you again on the email thread that includes your colleagues once it's out :)

**Comment by pchukwura** [comment]
Sweet! Thanks for clearing that up for me. We'll look for your email this
week.

Cheers

On Tue, Jan 27, 2015 at 3:37 PM, Harriet Lawrence <notifications@github.com>
wrote:

> Hey Patrick, thanks for checking in, sorry that it didn't end up going out
> yesterday. There were a couple of minor holdups getting all the metadata
> ready to go, but that's all resolved. I didn't end up deploying at all
> yesterday, but it will definitely happen this week. I'll ping you again on
> the email thread that includes your colleagues once it's out :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/segmentio/analytics.js-integrations/pull/382#issuecomment-71752329>
> .
>



-- 
-Patrick Chukwura

**Comment by harrietgrace** [comment]
Hey Patrick, once I deploy your integration, it will have some auto-generated docs that will only contain information about the settings available ([example here](https://segment.com/docs/integrations/adlearn-open-platform/)). If you'd like some more in-depth documentation listed there, you're welcome to email it to me at harriet@segment.com and I'll put it up :)

**Comment by pchukwura** [comment]
Thanks for letting me know. I'll take a look and send more documentation soon after it goes live. 

Also, when it goes live , do I talk to you about the marketing side of things, if not can you put me in touch please? 

And thanks again for all your help!

**Comment by amillet89** [comment]
Hi @pchukwura, for co-marketing can you send us an e-mail at integrations@segment.com and I'll put you in touch! thanks for your patience!

**Pull request merged**
