### PR TITLE
Remove extra script tag

### PR DESCRIPTION
**Pull request by MrTravisB**
@amillet89 Some how this got past all of us and is causing 2 version of our javascript to be loaded.

### CODE REVIEW

**Comment by f2prateek** [comment]
LGTM

**Comment by amillet89** [comment]
@MrTravisB to avoid going back and forth with incremental fixes I had a couple comments:

- in the identify call you're sending the userId both as a top-level argument and as a parameter in userAttributes, is that necessary?
- the casing is inconsistent, there's both user_id and firstName. 
- for the common traits, it's better to use the facade methods directly. for e.g. firstName: identify.firstName(). you can read more about these [here](https://github.com/segmentio/facade/blob/master/lib/identify.js#L138). this basically handles more cases, for e.g. if user is passing in first_name or firstName or pulling the first name from a 'name' trait.

thanks!

**Comment by amillet89** [comment]
oh and the actual change in question here looks good, we should of caught that earlier as well.

**Comment by MrTravisB** [comment]
@amillet89 thank you for pointing these out. I have updated the identify here to essentially mirror our server side mapping.

**Comment by amillet89** [comment]
@MrTravisB mind squashing the commits into one? then i think we're good to go.

**Comment by MrTravisB** [comment]
@amillet89 Sure thing. All done.

**Comment by amillet89** [comment]
lgtm

**Pull request merged**
