### PR TITLE
Taplytics.js Integration

### PR DESCRIPTION
**Pull request by nemo**
Added [Taplytics.js](https://github.com/taplytics/taplytics-js).

This is part of us fully integrating Segment on all fronts. See Android PR [here](https://github.com/segmentio/analytics-android/pull/285).

Super excited to get this merged in – happy to fix things up if they don't look right.

Thanks @amillet89 for helping me out with figuring out writing up the tests.

### CODE REVIEW

**Comment by f2prateek** [comment]
Noticed that group isn't supported here - is this deliberate? The existing iOS one doesn't either, but the Android PR does add support for it. It would be nice to have all implementations be as close to each other as possible.

**Comment by nemo** [comment]
@f2prateek thanks for bringing that up. We can actually support it easily, so I've included it here and we'll be sending an iOS PR to add it there too!

**Comment by amillet89** [comment]
looks good, thanks for the PR!

**Comment by nemo** [comment]
Awesome – thanks @amillet89!

**Pull request merged**
