### PR TITLE
Support Hero integration

### PR DESCRIPTION
**Pull request by floernoult**
Hi,

Here is a new integration for Support Hero. Along with this pull request, I sent you an email with the required test account, the .md file and our logo.
Also, we submitted the business survey last month and I just submitted the technical survey.

Hope everything is fine. Just let me know otherwise.

Regards,

Florian

### CODE REVIEW

**Comment by amillet89** [comment]
Looks good to me, thanks for contributing Florian!

**Comment by floernoult** [comment]
Great news! Thanks for merging :-)

**Comment by amillet89** [comment]
@floernoult happy to report that we released analytics.js and you should now see your integration in Segment! Let us know if you face any issues at friends@segment.com

**Comment by floernoult** [comment]
Awesome! Thanks a lot @amillet89. I'll test this asap.
Regards.

**Pull request merged**
