### PR TITLE
Implemented #alias for Vero

### PR DESCRIPTION
**Pull request by jylamont**
Hi team,

This is a quick pull request that will properly implement .alias for Vero's JS library. All are tests passing. Let me know if you have any questions/improvements/etc.

### CODE REVIEW

**Comment by lambtron** [comment]
@amillet89 @harrietgrace @ndhoule FYI. this came from a zendesk ticket.

**Comment by DirtyAnalytics** [comment]
also worth noting this PR brings the JS integration up to feature parity with the vero server-side integration, which is pretty important for docs and such: https://github.com/segmentio/integration-vero/blob/master/lib/mapper.js#L75-L90

**Comment by harrietgrace** [comment]
Thanks @jylamont, looks good! :)

**Comment by jylamont** [comment]
Awesome @harrietgrace, thanks!

**Pull request merged**
