### PR TITLE
support ecommerce events via fb conversion tracking

### PR DESCRIPTION
**Pull request by hden**
Mapping ecommerce events [doc](https://segment.com/docs/spec/ecommerce/) to Facebook audience [doc](https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-audiences/v2.3#setuppixel)

### CODE REVIEW

**Comment by hden** [comment]
related to #594

**Comment by sperand-io** [comment]
Thanks so much @hden! We really appreciate the contribution :)

One comment inline. As soon as we make that change we will get this out. We'll be reviewing pulls Thursday AM if you'd like to make the change yourself, otherwise we can make it and it will probably go out some time next week. Thanks again!

**Comment by hden** [comment]
Accidentally deleted a comment from @sperand-io 

> Rather than the long conditional switch on event name, we'd want to put the logic for each semantic event type on the prototype methods that are invoked when we receive them (ie. Completed Order, Added Product —> Facebook.prototype.completedOrder, Facebook.prototype.addedProduct), like so: https://github.com/segmentio/analytics.js-integrations/blob/master/lib/foxmetrics/index.js#L131-L133
> Implemented here:
https://github.com/segmentio/analytics.js-integration/blob/master/lib/protos.js#L323-L330
https://github.com/segmentio/analytics-events/blob/master/index.js
> That gives us case insensitivity on the event names and flexibility in the future should we need to change the spec :)

**Comment by sperand-io** [comment]
Thanks @hden, looks great!

I just realized something embarrassing that I should have caught before. I'm not yet certain this is actually the right place for us to add this logic. Of the two Facebook products we currently integrate with (Conversion Tracking and Custom Audiences), this seems to fall more under Custom Audiences (the integration for which is currently private). However, **Product Audiences** might beget its own *third* separate integration as well — we're not yet sure.

If it's okay with you, we'd like to reach out to some folks at FB to determine where this belongs, and once that's settled use your contribution with attribution in the appropriate place. Sound good?

**Comment by hden** [comment]
Sure :)

**Comment by ndhoule** [comment]
Landed in #120, closing.

**Pull request closed without merging**
