### PR TITLE
Add ecommerce revenue tracking to VWO

### PR DESCRIPTION
**Pull request by tikotzky**

### CODE REVIEW

**Comment by tikotzky** [comment]
Now that the tests are passing I rebased on top of master and all looks good.

Any chance of this getting merged soon?

**Comment by tikotzky** [comment]
@yields @ndhoule @f2prateek any way this can get merged :pray: :smiley:

**Comment by reinpk** [comment]
thanks so much @tikotzky and really sorry for the months of delay, really appreciate the clean pull request and we'll get this deployed on monday!

**Comment by tikotzky** [comment]
@reinpk Thanks! better late then never :wink:

**Pull request merged**
