### PR TITLE
Parsely integration

### PR DESCRIPTION
**Pull request by hbbtstar**
Bundled Parsely integration is here!

Brief overview of integration:

The script fires a pageview pixel and creates a div with configuration information (specifically, the user's API key) that our crawler needs to accurately track the page.

### CODE REVIEW

**Comment by amillet89** [comment]
@hbbtstar thanks for your contribution. Can you explain why this integration needs to be embedded in the browser? It looks like me like all this data can be collected by our analytics.js library in the browser and then sent to Parsely server-side. You can find documentation on how the server-side integrations work here: https://segment.com/docs/partners/direct-integration/. You can see example data of what is being sent by our library here: https://segment.com/docs/spec/#api-calls. we prefer server-side integrations because it allows you to receive data from customers that send data both from browser their servers, and mobile, and it allows us to replay historical data when onboarding customers.

**Comment by hbbtstar** [comment]
hi amillet!

Sure, I can clarify. The reason our integration needs to be embedded in the browser is because the client side code ensures we use/create existing user identifiers for network and first party uses, and without it we'd have to have some way for you to mimic our client-side sessionization.

Additionally, we have several client integration and verification tools that use PhantomJS to detect and validate the code on the page, and without the parsely-root div those checks will always fail, requiring us to manually override any client using Segment.

Let me know if any of this is unclear or you want more clarification, and thanks for the prompt turnaround on this!

Best,
-Xand

**Comment by amillet89** [comment]
hi @hbbtstar. thanks for providing that explanation. how are you defining sessionization? In analytics.js the session id is captured by the anonymousId field in each call, so this could still be provided in a server-side integration. The reason I suggested server-side is that with one integration you'd be able to have access to our mobile customers as well, and be able to replay historical data when onboarding customers which shortens the sales cycle considerably because customers see their own data in your tool from day 1 :)

quick technical points on this submission- you don't need to load the script manually on the page in the initialize call, instead u can use the `.tag` method on the integration object as shown in this example: https://github.com/segment-integrations/analytics.js-integration-comscore/blob/master/lib/index.js#L20

second important comment is that we strongly recommend against directly modifying the dom as you are doing to add the div element. many of our customers use backbone or angular and the entire body element will get replaced and so your span element with the apiKey will disappear. Best practice here is to include as a field on the global object, i.e. `window.parsely = { apiKey: apiKey };`. Since you're using phantomJS you should have access to this element when scanning the page. 

also, we like to keep high style standards, so please don't disable lint :)
http://www.parsely.com/docs/integration/tracking/faq.html#what-data-is-sent-by-default

thanks!

**Comment by msukmanowsky** [comment]
Howdy @amillet89, we'd really prefer to go a direct integration route. Server-side would require us to develop, maintain and scale a proxy system to take Segment requests and convert them to the request format that our pixel servers (and our downstream systems) expect and require. That's a pretty tall order for segment alone, not to mention if we had to also do this for similar technologies.

In addition, as @hbbtstar mentioned, the way Parse.ly creates and sends first-party and third-party user and session identifiers is different than what Segment would do here which creates inconsistency in our platform. Most customers get X, but segment.io customers may only get X-Y.

Most importantly though, we're also constantly adding more features to our JavaScript bundles to collect new data for our customers. With a segment server-side integration (or a more limited JS integration that doesn't use our JS bundle), Parse.ly customers would never have access to some of the new stuff we're currently working on.

Your final point on not adding a DIV element makes sense, but unfortunately our bootstrap code currently has a dependency on a div with `id="parsely-cfg"`, that said, if adding the DIV in the body is an issue, we could just go with a meta tag inside the `<head></head>` tags like so:

``` html
<head>
....
<meta id="parsely-cfg" data-parsely-site="<apikey>" />
</head>
```

Hope that all makes sense, lemme know if you have any questions!

**Comment by amillet89** [comment]
@msukmanowsky @hbbtstar thanks for the explanation.

the meta tag in the head is definitely an improvement. can you make this fix as well as the ones mentioned previously around the .tag method and style issues, and contribute a PR here: https://github.com/segment-integrations/analytics.js-integration-parsely. You can copy from this example: https://github.com/segment-integrations/analytics.js-integration-atatus 

thanks!

**Comment by hbbtstar** [comment]
@amillet89 thanks so much for all your help so far!

Would you be able to make a readme or something in the repo so I can issue a PR to it? Thanks!

https://github.com/segment-integrations/analytics.js-integration-parsely/issues/1

**Comment by amillet89** [comment]
whoops my bad @hbbtstar should be there now.

**Pull request closed without merging**
