### PR TITLE
added productId to viewed product event

### PR DESCRIPTION
**Pull request by f2prateek**

### CODE REVIEW

**Comment by sperand-io** [comment]
not sure this is the right implementation :/

I don't think they have a `trackProductId` method — the code jake linked to here was for their old js api: http://support.perfectaudience.com/knowledgebase/articles/318806-setting-up-dynamic-facebook-news-feed-retargeting

I re-wrote the integration to use the async API (`_pq.push`) a few months ago: http://support.perfectaudience.com/knowledgebase/articles/212490-visitor-tracking-api

... And supported this by mapping the `properties.sku` field in the `trackProduct` method:



The question I guess is whether we should be mapping `properties.id` rather than `properties.sku`

@DirtyAnalytics thoughts?

**Comment by DirtyAnalytics** [comment]
a product's `sku` and `id` could be fundamentally different, or could be the same

the assumption by separating those 2 things is that `id` refers to a database ID and `sku` is the publicly visible identifier for a product

so maybe all your products in your store have some ID like a 9 digit integer or something, but each product will also have a SKU that is usually more user friendly, for example if my store was called Jake's Scarf Store with 3 items I might have these `id` and `sku` combinations:

- Red Scarf
  - `id` = `197232`
  - `sku` = `J-SR`
- Blue Scarf
  - `id`: `197237`
  - `sku` = `J-SB`
- Green Scarf
  - `id`: `197235`
  - `sku` = `J-SG`

In some ecommerce platforms they use SKU for the only identifier, so in that case `id` = `sku`, and sometimes a platform might have an `id`, but the user chooses to only use the `sku`, in which case they'd be the same again, but the ideal situation they are different.

**Comment by sperand-io** [comment]
dang, thanks so much for the background info. so which should we map then? `id`?

**Comment by DirtyAnalytics** [comment]
I think it would depend on the best practice for perfect audience but I assume it's `id` in this case

**Comment by reinpk** [comment]
looks great @n2parks !

**Pull request merged**
