### PR TITLE
Quantcast: added support for repeat/new customer flags

### PR DESCRIPTION
**Pull request by sperand-io**
[Support ticket and discussion around how to send this data w/ Quantcast folks here](https://segment.zendesk.com/agent/tickets/25782)

@ndhoule @f2prateek @amillet89

### CODE REVIEW

**Comment by f2prateek** [comment]
@sperand-io already implemented (probably completely wrongly) here https://github.com/segmentio/analytics.js-integrations/pull/568. We still need a discussion around the spec part of this. @amillet89 can fill you in here.

**Comment by sperand-io** [comment]
@f2prateek @amillet89 ahh, not sure how i missed that! thanks for the heads up. 

Will catch up with you both in person about this but wanted to jot some thoughts:

- I think we need to *omit* the label when the `repeat` property is missing from the event. We don't want to just send a `new` label for every completed order that hadn't yet seen the `repeat` spec requirement or who deliberate omits it.

- in addition, we should consider using the `.fp_customer.` label schema requested by their integration specialists. 

Here's the thinking I had given that we standardized and documented `repeat` as the semantic property:

| `properties.repeat` | qcast label |
| --------| --------| 
|`undefined` | n/a |
|`true`|`_fp.customer.repeat`|
|`false`|`_fp.customer.new` |

**Comment by f2prateek** [comment]
Yup, makes sens to me. That was on our To-Do before merging the PR, but we weren't sure if repeat is something we we want to support for this integration.

**Comment by amillet89** [comment]
lgtm!

**Pull request merged**
