### PR TITLE
Update Appcues Integration

### PR DESCRIPTION
**Pull request by hijonathan**
This points to the new embed script, which also demands a lot less as part of its initialization. Fixed the tests to match.

### CODE REVIEW

**Comment by hijonathan** [comment]
Any feedback?

**Comment by hijonathan** [comment]
:8ball:

**Comment by hijonathan** [comment]
@lancejpollard @reinpk any chance someone can take a look at this? This is a follow-up to #180.

**Comment by reinpk** [comment]
nice this is much cleaner! sorry for the radio silence!

**Comment by hijonathan** [comment]
Thanks @reinpk!

**Pull request merged**
