### PR TITLE
Update Amplitude integration to v2.0.2

### PR DESCRIPTION
**Pull request by curtisliu**
Hey Segment,

Recently we made a switch to build our JS library with duo --standalone, and I think it's causing issues with passing the load test (I suspect similar to https://github.com/duojs/duo/pull/361#issuecomment-60429183). Can you help me get the tests passing again?

Thanks!

### CODE REVIEW

**Comment by yields** [comment]
hey @curtisliu, sorry for the crazy delay here!

I think the issue is that on the test page we load requirejs (AMD) just to make sure that everything works on site that use AMD too, since you're using UMD (--standalone) in the lib, it checks and sees that there's a global `define()`, so it will export `amplitude` with `define`.

To solve this you'll have to check if `define()` is available and load using `window.require` and if not, just use the global `window.amplitude`.

Bugsnag js lib is UMD too, so here's how i [load](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/bugsnag/index.js#L43-L55) it, you can just copy paste and it will work :)

Let me know if that helps!

**Comment by curtisliu** [comment]
Thanks! That was really helpful. Turns out we also had some AMD conflicting code that we needed to fix as well. Should be good to go, please take a look!

**Comment by yields** [comment]
lgtm! once you squash those commits we can merge :)

**Comment by curtisliu** [comment]
Done

**Comment by yields** [comment]
thanks!

**Comment by guillaumecabane** [comment]
Hey, we still have the AMD issue here. Is this deployed ?

**Comment by yields** [comment]
yes, it is, what's the issue?

**Comment by arnaud-lb** [comment]
@yields: The integration [checks](https://github.com/segmentio/analytics.js-integrations/blob/2f90b6f79514deb510b7615146da25af6d13268a/lib/amplitude/index.js#L14) that there is a window.define && define.amd, however it doesn't [use the result of this check](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/amplitude/index.js#L51) immediately. In the meantime, lots of things can happen, e.g. an amd-compatible define() function could be defined.

As a result, here is what seem to be happening to us:

 - analytics.js loads, and sets `var umd = false`
 - require.js loads
 - Amplitude.prototype.initialize is called; with the closed variable `umd` set to `false`
 - amplitude.js is [loaded using a `<script>` tag](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/amplitude/index.js#L59), but then it sees a `window.define && define.amd` and calls `require("1")`
 - require.js throws `Error: Mismatched anonymous define() module: function (){return require("1")}
http://requirejs.org/docs/errors.html#mismatch`

**Comment by yields** [comment]
@arnaud-lb 

gotcha, we load require.js in the [tests](https://github.com/segmentio/analytics.js-integrations/blob/master/test/index.html#L7) so it should work, but i've never really used and at all, so maybe i've set it up wrong or something, a simple html file that reproduces this would help a lot!

any chance of a simple html file that reproduces this?

**Comment by curtisliu** [comment]
I can chime in here, as it seems to be the same issue as https://github.com/amplitude/Amplitude-Javascript/issues/3. A quick fix is to ensure require.js is loaded before analytics.js is loaded, but it would be nice to not rely on that ordering. We'll probably switch to using --global to build the javascript.

**Comment by cdll** [comment]
oh, who could please help me with @yields 's reply, i really need the code demo at https://github.com/segmentio/analytics.js-integrations/blob/master/lib/bugsnag/index.js#L43-L55

**Comment by yields** [comment]
@cdll i think the above should be https://github.com/segment-integrations/analytics.js-integration-bugsnag/blob/master/lib/index.js#L42-L49 since we separated the libs.

**Comment by yields** [comment]
@cdll what's the issue you're seeing?

**Comment by cdll** [comment]
@yields ,the issues bellow:
`t.amplitude.runQueuedFunctions is not a function`
and
`Mismatched anonymous define() module: function (){return require("1")}`

i just simply used the code snippet:
`(function(t,e){
      var n=t.amplitude||{};
      var r=e.createElement("script");
      r.type="text/javascript";
      r.async=true;
      r.src="https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.6.1-min.gz.js";
      r.addEventListener('load', function(){t.amplitude.runQueuedFunctions()});
      var s=e.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(r,s);
      var i=function(){this._q=[];return this};
      function o(t){
        i.prototype[t]=function(){this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));return this;}}
      var a=["add","set","setOnce","unset"];for(var u=0;u<a.length;u++){o(a[u]);}
      n.Identify=i;n._q=[];function c(t){n[t]=function(){n._q.push([t].concat(Array.prototype.slice.call(arguments,0)));}}
      var l=["init","logEvent","logRevenue","setUserId","setUserProperties","setOptOut","setVersionName","setDomain","setDeviceId","setGlobalUserProperties","identify"];
      for(var p=0;p<l.length;p++){c(l[p])}t.amplitude=n}
    )(window,document);`

**Comment by cdll** [comment]
oops, i change the onload callback into an 'addEventListener', but the origin onload event also has the error.

**Comment by cdll** [comment]
@yields ok, thanks a lot. i 've just use the direct require method to fit my need, cause i got some old script that i want to use before. now i abandon to use the old script. thank u all the same~

**Pull request merged**
